name: Semgrep SAST

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  semgrep:
    runs-on: ubuntu-latest

    container: returntocorp/semgrep

    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep
        continue-on-error: ${{ github.ref != 'refs/heads/main' }}
        run: |
          semgrep ci \
            --config=p/ci \
            --config=p/java \
            --config=p/secrets